module.exports = {
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  ACCESS_TOKEN_EXPIRES: process.env.ACCESS_TOKEN_EXPIRES,
  JWT_REFRESH_TOKEN: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRES: process.env.REFRESH_TOKEN_EXPIRES,
  ENCRYPT_KEY: process.env.ENCRYPT_KEY,
  //Node mailer options
  EMAIL_SERVICE: process.env.EMAIL_SERVICE,
  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  MAIL_CONFIRMATION_TOKEN: process.env.MAIL_CONFIRMATION_TOKEN,
  CONFIRMATION_URL: process.env.CONFIRMATION_URL,

  FRONTEND_ENDPOINT: process.env.FRONTEND_ENDPOINT,
  BACKEND_ENDPOINT: process.env.BACKEND_ENDPOINT,
};
